######################################################################
# Automatically generated by qmake (3.0) Wed Jul 20 22:19:34 2016
######################################################################

TEMPLATE = app
TARGET = formex
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += form.h
SOURCES += form.cpp formex.cpp
