######################################################################
# Automatically generated by qmake (3.0) Wed Jul 20 22:19:14 2016
######################################################################

TEMPLATE = app
TARGET = reflex
INCLUDEPATH += .

# Input
HEADERS += hammer.h knee.h
SOURCES += reflex.cpp
