######################################################################
# Automatically generated by qmake (3.0) Sun Aug 14 18:12:10 2016
######################################################################

TEMPLATE = app
TARGET = twitter
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += multiwin.h Tweet.h TwitEng.h User.h
SOURCES += main.cpp multiwin.cpp TwitEng.cpp User.cpp
