######################################################################
# Automatically generated by qmake (3.0) Wed Jul 20 22:15:46 2016
######################################################################

TEMPLATE = app
TARGET = lec_ttt
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += ttt.h ttt_board.h ttt_button.h
SOURCES += main.cpp ttt.cpp ttt_board.cpp ttt_button.cpp
