######################################################################
# Automatically generated by qmake (3.0) Wed Jul 20 21:56:41 2016
######################################################################

TEMPLATE = app
TARGET = multiwin
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += multiwin.h
SOURCES += main.cpp multiwin.cpp
